version = 4.2.0
archive_dir = /etc/letsencrypt/archive/sharesampatti.com
cert = /etc/letsencrypt/live/sharesampatti.com/cert.pem
privkey = /etc/letsencrypt/live/sharesampatti.com/privkey.pem
chain = /etc/letsencrypt/live/sharesampatti.com/chain.pem
fullchain = /etc/letsencrypt/live/sharesampatti.com/fullchain.pem

# Options used in the renewal process
[renewalparams]
account = d3568c311b77be04ad0301f919f3c3de
authenticator = webroot
webroot_path = /var/www/certbot,
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[[webroot_map]]
sharesampatti.com = /var/www/certbot
www.sharesampatti.com = /var/www/certbot
